/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import control.CustomerDAO;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Customer;

public class AplikasiUtama extends javax.swing.JFrame {
    panelCustomer customer = new panelCustomer();
    panelDetail detail = new panelDetail();
    panelPegawai pegawai = new panelPegawai();
    panelPemesanan pemesanan = new panelPemesanan();
    panelProduksi produksi = new panelProduksi();
    panelRole role = new panelRole();
    panelTransaksi transaksi = new panelTransaksi();
    AboutUS about = new AboutUS();
    DefaultTableModel dtmCust;
    CustomerDAO daoCust;
    
    public AplikasiUtama() {
        initComponents();
        this.add(customer);
        this.add(detail);
        this.add(pegawai);
        this.add(pemesanan);
        this.add(produksi);
        this.add(role);
        this.add(transaksi);
        this.add(about);
        daoCust = new CustomerDAO();
        dtmCust = (DefaultTableModel) tabelCust.getModel();
        DataCust();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelLogin = new javax.swing.JPanel();
        user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        panelHome = new javax.swing.JPanel();
        tblCust = new javax.swing.JScrollPane();
        tabelCust = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cust = new javax.swing.JMenuItem();
        det = new javax.swing.JMenuItem();
        peg = new javax.swing.JMenuItem();
        pem = new javax.swing.JMenuItem();
        pro = new javax.swing.JMenuItem();
        rol = new javax.swing.JMenuItem();
        tra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelLogin.setLayout(new java.awt.GridBagLayout());

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(93, 18, 0, 0);
        panelLogin.add(user, gridBagConstraints);

        jLabel1.setText("USERNAME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(96, 263, 0, 0);
        panelLogin.add(jLabel1, gridBagConstraints);

        jLabel2.setText("PASSWORD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 262, 0, 0);
        panelLogin.add(jLabel2, gridBagConstraints);

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 237, 0);
        panelLogin.add(jButton1, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("APLIKASI IMPLEMENTASI DATABASE PERCETAKAN XPELITA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(111, 128, 0, 95);
        panelLogin.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 18, 0, 0);
        panelLogin.add(pass, gridBagConstraints);

        getContentPane().add(panelLogin, "card2");

        panelHome.setLayout(new java.awt.GridBagLayout());

        tabelCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Customer", "Nama", "No Telp.", "Jenis Kelamin", "Email", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCust.setViewportView(tabelCust);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 994;
        gridBagConstraints.ipady = 634;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 13, 12);
        panelHome.add(tblCust, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("DATA CUSTOMER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 422, 0, 0);
        panelHome.add(jLabel3, gridBagConstraints);

        getContentPane().add(panelHome, "card3");

        jMenu1.setText("File");

        jMenuItem3.setText("LogOut");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("About Us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master Data");

        cust.setText("Customer");
        cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custActionPerformed(evt);
            }
        });
        jMenu2.add(cust);

        det.setText("Detail Pemesanan");
        det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detActionPerformed(evt);
            }
        });
        jMenu2.add(det);

        peg.setText("Pegawai");
        peg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegActionPerformed(evt);
            }
        });
        jMenu2.add(peg);

        pem.setText("Pemesanan");
        pem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemActionPerformed(evt);
            }
        });
        jMenu2.add(pem);

        pro.setText("Produksi");
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        jMenu2.add(pro);

        rol.setText("Role");
        rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolActionPerformed(evt);
            }
        });
        jMenu2.add(rol);

        tra.setText("Transaksi");
        tra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traActionPerformed(evt);
            }
        });
        jMenu2.add(tra);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (user.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username is required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (pass.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Password Pinjam is required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (user.getText().equals("admin")  && pass.getText().equals("admin12345*")) {
            JOptionPane.showMessageDialog(this, "Welcome admin", "Information Message", JOptionPane.INFORMATION_MESSAGE);
            home();
        }else{
            JOptionPane.showMessageDialog(this, "Username atau Password salah", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        produksix();
    }//GEN-LAST:event_proActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JOptionPane.showMessageDialog(this, "Good bye Admin! \nExit", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(this, "Good bye Admin! \nLogOut", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        logout();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custActionPerformed
        customerx();
    }//GEN-LAST:event_custActionPerformed

    private void detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detActionPerformed
        detailx();
    }//GEN-LAST:event_detActionPerformed

    private void pegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegActionPerformed
        pegawaix();
    }//GEN-LAST:event_pegActionPerformed

    private void pemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemActionPerformed
       pemesananx();
    }//GEN-LAST:event_pemActionPerformed

    private void rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolActionPerformed
        rolex();
    }//GEN-LAST:event_rolActionPerformed

    private void traActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traActionPerformed
        transaksix();
    }//GEN-LAST:event_traActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        aboutx();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cust;
    private javax.swing.JMenuItem det;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField pass;
    private javax.swing.JMenuItem peg;
    private javax.swing.JMenuItem pem;
    private javax.swing.JMenuItem pro;
    private javax.swing.JMenuItem rol;
    private javax.swing.JTable tabelCust;
    private javax.swing.JScrollPane tblCust;
    private javax.swing.JMenuItem tra;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
    private void logout() {
        jMenuBar1.setVisible(false);
        panelLogin.setVisible(true);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
        about.setVisible(false);
    }
    
    private void home() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        DataCust();
        panelHome.setVisible(true);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
        about.setVisible(false);
    }
    
    private void customerx() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(true);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
        about.setVisible(false);
    }
    
    private void detailx() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(true);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
        about.setVisible(false);
    }
    
    private void pegawaix() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(true);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
        about.setVisible(false);
    }
     
    private void pemesananx() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(true);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
        about.setVisible(false);
    }
        
    private void produksix() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(true);
        role.setVisible(false);
        transaksi.setVisible(false);
        about.setVisible(false);
    }
        
    private void rolex() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(true);
        transaksi.setVisible(false);
        about.setVisible(false);
    }
         
    private void transaksix() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(true);
        about.setVisible(false);
    }
    
        private void aboutx() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
        about.setVisible(true);
    }

        
    public void DataCust() {
        dtmCust.getDataVector().removeAllElements();
        for (Customer b : daoCust.getAllData()) {
            dtmCust.addRow(new Object[]{
                b.getIdCustomer(),
                b.getNamaCustomer(),
                b.getNoTelp(),
                b.getJenisKelamin(),
                b.getEmail(),
                b.getAlamat()
            });
        }
    }
    public class formatDate{
        public static SimpleDateFormat sdf = new SimpleDateFormat("EEE, dd MMM yyyy");
    }
}
